### ISSUE TITLE
Acoustic Fingerpring Plugin not working - AtributeError on 3.8.0

### ISSUE THREAD

**Issue by sljunkie** [quodlibet/quodlibet#2192]
This plugin isn't working on quodlibet/ex falso since 3.8.0. Whenever I try to search album data with this plugin I get this error:

`E: 20.692: qltk.songsmenu.__handle: acoustid.py:265:__init__: AttributeError: class Queue has no attribute 'Queue'
`
on the terminal
