### ISSUE TITLE
build on osx 10.12 broken, kinda

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#2069]
building on 10.12 and running on something older leads to this:

```
dyld: lazy symbol binding failed: Symbol not found: _getentropy
  Referenced from: /Users/travis/build/quodlibet/quodlibet/_mount/QuodLibet.app/Contents/Resources/lib/libpython2.7.dylib
  Expected in: /usr/lib/libSystem.B.dylib
dyld: Symbol not found: _getentropy
  Referenced from: /Users/travis/build/quodlibet/quodlibet/_mount/QuodLibet.app/Contents/Resources/lib/libpython2.7.dylib
  Expected in: /usr/lib/libSystem.B.dylib
../_mount/QuodLibet.app/Contents/MacOS/run: line 62:  2209 Trace/BPT trap: 5       "$PYTHON" "$@"
```

**Comment by lazka** [comment]
Added a comment to the cpython bug tracker: https://bugs.python.org/issue28341#msg279299

**Comment by CreamyCookie** [comment]
@lazka Is this still an issue?

**Comment by lazka** [comment]
It is, but I've fallen back to building releases on 10.11.

I've added something to the README now.
